server:
  port: 9002
spring:
  application:
    name: feign-consumer-demo
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
  instance:
    hostname: localhost   